### ISSUE TITLE
Quiz Feedback - Level 2

### ISSUE THREAD

**Issue by aditiopangestu** [syahrizalakbar/hsi-sandbox-quiz#1]
Alhamdulillah, secara functional aman mas, tapi penggunaan ref perlu diperhatikan, silahkan membaca ini

1. Sebaiknya ref tidak digunakan untuk mengubah DOM yang sudah diatur oleh React, silahkan baca di https://beta.reactjs.org/learn/manipulating-the-dom-with-refs#best-practices-for-dom-manipulation-with-refs
2. Sebaiknya ref tidak digunakan untuk menyimpan nilai yang dibaca saat rendering, silahkan baca di https://beta.reactjs.org/learn/referencing-values-with-refs#best-practices-for-refs

Untuk dua kasus tersebut sebaiknya menggunakan useState atau useReducer, silahkan baca di https://beta.reactjs.org/learn/managing-state

Silahkan diupdate source code nya, terima kasih, semoga Allah mudahkan

**Comment by syahrizalakbar** [comment]
Sudah di update ya mas

[c3b7792](https://github.com/syahrizalakbar/hsi-sandbox-quiz/commit/c3b7792cc4d62d44d93417cf01aff248fb355630)

**Comment by aditiopangestu** [comment]
mas, ada feedback lagi untuk handle focus, dari acceptance criteria, focus diarahakan ke field yang error setelah klik "Next Step", bukan setiap render. Disebut setiap render karena dilihat dari penggunaan useEffect tanpa dependencies, seminimal mungkin kita menggunakan useEffect, bisa baca di https://react.dev/learn/you-might-not-need-an-effect. Kalau dilihat lebih dalam potongan source dibawah ini untuk mengatasi bug yang dihasilkan oleh useEffect.
<img width="307" alt="Screen Shot 2023-03-20 at 05 53 51" src="https://user-images.githubusercontent.com/17538343/226215030-160b0d09-610d-463a-b79c-a4a108e5dcc1.png">

Cara menghandle focus, bisa menggunakan 4 useRef yang di assign ke masing masing TextField, lalu handle fokus di `onNext`.

**Comment by syahrizalakbar** [comment]
Baik mas, sudah diupdate kembali codenya sesuai feedback

**Comment by aditiopangestu** [comment]
masih ada feedback ya mas, penggunaan `useRef` tidak boleh di dalam loop, silahkan pelajari https://react.dev/learn/manipulating-the-dom-with-refs#how-to-manage-a-list-of-refs-using-a-ref-callback
