### ISSUE TITLE
Feedback Quiz Lv4-form

### ISSUE THREAD

**Issue by udiiin** [syahrizalakbar/hsi-sandbox-quiz#3]
Halo Mas @syahrizalakbar, terima kasih utk submittionnya... 🙏 

Saya ada beberapa feedback:

**1.)**  
Penggunaan code ini: `availableSteps = React.useMemo(() => [1, 2, 3, 4], [])`,  
Itu bisa dikeluarkan dari component, dan tidak perlu lagi menggunakan `useMemo`.

**2.)**  
`lastStep` tidak perlu menggunakan `useMemo`, karena tipenya primitive (number), dan tidak ada komputasi yg berat.

**3.)**  
Coba diexplor utk menggunakan 1x `useForm` saja, yg mencakup keseluruhan step.

**4.)**  
`handleSubmit` di `useForm` bukan sebuah promise, sehingga tidak perlu `.then`.

**5.)**  
Penggunaan `e.preventDefault()` di onBack & onNext tidak diperlukan.

**6.)**  
Validasi phone number belum sesuai kriteria:
> _no hp harus diawali dengan “08” **dan jumlah angka selanjutnya minimal 8 dan maksimal 12**_

.

Semoga dimudahkan, barokallaahu fiik...

**Comment by syahrizalakbar** [comment]
sudah saya perbaiki ya mas, sebelumnya terimakasih atas feedbacknya, oiya untuk nomor 4 sudah saya hilangkan .thennya, tapi kenapa di vscode saya di keterangannya promise ya mas, makanya waktu saya kasih then hehe

 
<img width="766" alt="Screenshot 2023-08-02 at 19 51 20" src="https://github.com/syahrizalakbar/hsi-sandbox-quiz/assets/27173560/679d6655-343b-447c-8cc4-bda9471b5ae4">

**Comment by udiiin** [comment]
Saya barusan tes di https://1-form-submission-syahrizalakbar.vercel.app/ ada issue:

1. Belum ada placeholder seperti yg dicontohkan di https://docs.google.com/document/d/1lFeTyfY0OKIshY0PIBJU_z29HVrFreDw7-gsYgoghvg/edit?usp=sharing 
2. Validasi phone number masih bisa lolos hanya dengan mengisi "08123"

<img width="467" alt="Screen Shot 2023-08-05 at 16 18 33" src="https://github.com/syahrizalakbar/hsi-sandbox-quiz/assets/129339659/c4022d27-e5b5-4c79-858a-2bee6fb45656">

**Comment by syahrizalakbar** [comment]
Baik mas, sudah saya tambahkan mas hehe lupa saya di deploy juga

**Comment by udiiin** [comment]
Sipp mantab mas, udah oke ✅
