### ISSUE TITLE
Feedback Quiz Lv4-blog

### ISSUE THREAD

**Issue by udiiin** [syahrizalakbar/hsi-sandbox-quiz#4]
Terima kasih utk submissionnya mas..

Overall sudah oke ✅  
Jadi di sini saya sekedar mau kasih info tambahan aja..

**1.)**  
Code ini:
```
{query.data?.pages?.map((group, index) => {
  return (
    <Fragment key={index}>
      {group.data?.map((article, _) => (
        <div key={article.id} className="mb-16">
```
Bisa dipersimpel menjadi:
```
const articles = query.data?.pages.flatMap((page) => page.data);

// jadi di bawah tinggal gini:

{articles.map((article) => {
  return (
    <div key={article.id}>
```

**2.)**  
Usahakan konsisten dalam penggunaan optional chaining.  
Contoh yg tidak konsisten:
```
<>
  <div>{data.cat}</div>
  <div>{data?.fish}</div>
<>
```
Seharusnya di dalam 1 block yg sama, `data` pasti sama, jika di `data.cat` sudah yakin bahwa data pasti sebuah object, maka seharusnya di `data?.fish` tidak perlu optional chainning.

**Comment by syahrizalakbar** [comment]
sudah saya perbaiki ya mas, terimakasih feedbacknya

**Comment by udiiin** [comment]
Saya ada minor feedback lagi mas, ini belum konsisten _optional chaining_nya..

Ada `article.thumbnal`, ada `article?.title`, dll..

Pilihannya 2:
- Keduanya sama2 pakai optional chaining, atau
- Keduanya sama2 tidak pakai optional chaining

<img width="314" alt="Screen Shot 2023-08-05 at 16 17 05" src="https://github.com/syahrizalakbar/hsi-sandbox-quiz/assets/129339659/fd1c6cf5-ca42-4b9c-b8c6-d92f21b4c2e8">

Seperti penjelasan saya di atas terkait konsistensi optional chaining.

**Comment by syahrizalakbar** [comment]
Baik mas, sudah saya perbaiki di commit [https://github.com/syahrizalakbar/hsi-sandbox-quiz/commit/01d1cf2f095bbc5387cdb4501efaa0583769a5a4](url), tapi mas untuk chaining yang ini,

<img width="548" alt="Screenshot 2023-08-05 at 23 08 59" src="https://github.com/syahrizalakbar/hsi-sandbox-quiz/assets/27173560/7c068cec-0798-4bd5-a03e-6b8b7f9a79d2">

disini article thumbnail dan title tidak pakai optional chaining dikarenakan sudah ada pengecekan diatasnya article?.thumbnail && ...  sedangkan attribute alt dia tidak boleh null, jadinya saya kasih default valuenya ""

atau bagusnya gimana ya mas, apakah sebelum return itu dicek dulu apakah article itu null atau tidak, sehingga nanti yang dibawahnya semuanya tidak pakai optional chaining lagi?

**Comment by afiiif** [comment]
Oh iya, sipp2, mantab 👍 

Udah oke mas... ✅

**Comment by udiiin** [comment]
Oiya, sipp2 👍 

Udah oke mas ✅
